apiVersion: apps/v1
kind: Deployment
metadata:
  name: mp3-play-deployment
  labels:
    app: mp3-play
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mp3-play
  template:
    metadata:
      labels:
        app: mp3-play
    spec:
      containers:
      - name: mp3-play
        image: mp3-play:1.0
        ports:
        - containerPort: 5000