apiVersion: v1
kind: Service
metadata:
  name: mp3-play-loadbalancer
spec:
  selector:
    app: mp3-play
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80 # Any port
      targetPort: 5000 # Same as the Deployment (in fairness, same as the Pods)